import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";

import "./golbals.css";
import React from "react";

const geist = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  trends: React.ReactNode;
  users: React.ReactNode;
}

export default function Layout({ children, trends, users }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        style={{ maxWidth: 480, margin: "auto" }}
        className={`${geist.variable} ${geistMono.variable}`}
      >
        <nav
          style={{
            padding: "16px 0px",
            display: "flex",
            gap: 16,
            borderBottom: "1px solid #eee",
            marginBottom: 16,
          }}
        >
          <Link href="/">Home</Link>
          <Link href="/feed">Feed</Link>
          <Link href="/search">Search</Link>
          <Link href="/settings">Settings</Link>
        </nav>
        <div style={{ display: "flex", gap: 16 }}>
          <main style={{ flex: 2 }}> {children} </main>
          <p
            style={{
              flex: 1,
              display: "flex",
              flexDirection: "column",
              gap: 16,
            }}
          >
            {trends} {users}
          </p>
        </div>
      </body>
    </html>
  );
}
